<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>mdemu</RootNamespace>
    <AssemblyName>mdemu</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="MDComm.fs" />
    <Compile Include="mdemu.fs" />
  </ItemGroup>
</Project>
